name: Self-Hosted Runner Workflow

on:
  # allow a manual run 
  workflow_dispatch:
  schedule:
    # This cron expression runs the workflow every 10 minutes
    - cron: "*/60 * * * *"

jobs:
  create-file:
    runs-on: [self-hosted, macos, arm]
    steps:
      - name: Create tutu.txt file
        run: |
          echo "This is a file created by GitHub Actions" > tutu.txt
